"""Create user models

Revision ID: 8f7a06e769a9
Revises: 1a31ce608336
Create Date: 2025-04-21 12:07:33.155580

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8f7a06e769a9'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False))
    op.add_column('item', sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=True))
    op.add_column('item', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=True))
    op.add_column('item', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('item', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('item', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False))
    op.add_column('item', sa.Column('image', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=True))
    op.add_column('item', sa.Column('stock', sa.Integer(), nullable=False))
    op.alter_column('item', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10000),
               existing_nullable=False)
    op.alter_column('item', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10000),
               existing_nullable=True)
    op.add_column('user', sa.Column('tv_count', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('audio_count', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('laptop_count', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('mobile_count', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('gaming_count', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('appliances_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'appliances_count')
    op.drop_column('user', 'gaming_count')
    op.drop_column('user', 'mobile_count')
    op.drop_column('user', 'laptop_count')
    op.drop_column('user', 'audio_count')
    op.drop_column('user', 'tv_count')
    op.alter_column('item', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('item', 'title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('item', 'stock')
    op.drop_column('item', 'image')
    op.drop_column('item', 'category')
    op.drop_column('item', 'discount')
    op.drop_column('item', 'price')
    op.drop_column('item', 'color')
    op.drop_column('item', 'model')
    op.drop_column('item', 'brand')
    # ### end Alembic commands ###
